apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-content-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-content-app
  template:
    metadata:
      labels:
        app: grpc-content-app
    spec:
      containers:
        - name: grpc-content-app
          image: mehmetalitaskan/spring-grpc:grpc-content-micro
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-content-service
spec:
  selector:
    app: grpc-content-app
  ports:
    - port: 9595
      protocol: TCP
      targetPort: 9595
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobilebff-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobilebff-app
  template:
    metadata:
      labels:
        app: mobilebff-app
    spec:
      containers:
        - name: mobilebff-app
          image: mehmetalitaskan/grpc-micro:springboot-grpc-mobile-bff-4
          env:
            - name: GRPC_CLIENT_content_ADDRESS
              value: static://content-service:9595
---
apiVersion: v1
kind: Service
metadata:
  name: mobilebff-service
spec:
  selector:
    app: mobilebff-app
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080