apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobilebff-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobilebff-app
  template:
    metadata:
      labels:
        app: mobilebff-app
    spec:
      containers:
        - name: mobilebff-app
          image: mehmetalitaskan/bff:mobilebff-app-3
          env:
            - name: GRPC_CLIENT_CONTENT_ADDRESS
              value: static://content-micro-service:6565
---
apiVersion: v1
kind: Service
metadata:
  name: mobilebff-service
spec:
  selector:
    app: mobilebff-app
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080